<a href="https://colab.research.google.com/github/Maciej7410/Pandas-and-data-science/blob/main/Pandas_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Learning Pandas and Numpy libraly
- [Download librales](#scrollTo=import)
- [Numpy - typy danych](#scrollTo=numpy)
- [Działania na tablicach](#scrollTo=dzialania)

# Import

In [1]:
import pandas as pd
import numpy as np


# Numpy
Tworzenie tablic

In [16]:
A = np.array([2,3,4,5], dtype='float')
B = np.array([123,123,124], dtype=np.uint8) # możemy narzucić 8 bitową liczbę aby oszczędzić pamięć u - od zera
C = np.array([True,True,False])
A.shape # wypisuje rozmiar tablicy 
B.dtype, A.dtype, C.dtype

((4,), dtype('uint8'), dtype('float64'), dtype('bool'))

In [52]:
np.zeros(shape=(5,5),dtype='int') # tworzy tablicę z samymi zerami typ danych domyślnych float
np.ones(shape=(5,5)) # wstawia same jedynki
np.full(shape=(3,3), fill_value='pa')
np.arange(10) # tworzy dane tak jak range w pythonie
np.arange(start=45, stop=23, step=-2)
np.linspace(start=0, stop=1, num=10) # tworzy tablicę o równych wartościach o num ilości elementów
A = np.arange(15)
B = A.reshape((3,5)) # przetwarza tablicę na wymagany wymiar - jak nie będzie to możliwe wyświetli błąd
B.reshape(3,-1) # tworzy tablicę o 2 wierszach a -1 oznacza że python stworzy taką tablicę jak będzie istniała



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# Dzialania
### Działania na tablicach

In [60]:
A = np.array([2, 5, 8, 9])
B = np.array([4, -2, 1, 6])
A*B # możemy + - * / tablicę
A+3
C = A+3*B
print(A,B,C)
np.add()

[2 5 8 9] [ 4 -2  1  6] [14 -1 11 27]


In [58]:
A/B

array([ 0.5, -2.5,  8. ,  1.5])